package model

import (
	"fmt"

	"github.com/pixty/console/common"
)

type (
	Id int64

	// Organization DO.
	Organization struct {
		Id   Id
		Name string
	}

	// FieldInfo - describes a field of profile metadata
	FieldInfo struct {
		OrgId       Id
		FieldId     Id
		FieldType   FieldType
		DisplayName string
	}

	// Type of the field please see FLD_TYPE_ constants below
	FieldType string

	// User DO
	User struct {
		Id    Id
		Login string
	}

	// Camera DO
	Camera struct {
		Id         common.Id // friendly camera name
		OrgId      Id
		AcceessKey string
		SecretKey  string
	}

	// A person DO
	Person struct {
		// Person id is generated by Frame Processor
		Id         common.Id
		CamId      common.Id
		LastSeenAt common.Timestamp
		ProfileId  Id
		PictureId  common.Id // avatar
		MatchGroup common.Id
	}

	// Point on a 2D plane
	Point struct {
		X int `json:"x"`
		Y int `json:"y"`
	}

	// A rectangle on a 2D plane
	Rectangle struct {
		LeftTop     Point `json:"leftTop"`
		RightBottom Point `json:"rightBottom"`
	}

	// A size on 2D plane
	Size struct {
		Width  int `json:"Width" bson:"width"`
		Height int `json:"Height" bson:"height"`
	}

	// A face description DO
	Face struct {
		Id          Id
		PersonId    common.Id
		CapturedAt  common.Timestamp
		ImageId     common.Id
		Rect        Rectangle
		FaceImageId common.Id
		V128D       common.V128D
	}

	// An organization profile's information
	Profile struct {
		ProfileId Id
		OrgId     Id
		PictureId common.Id // avatar
	}

	ProfileMeta struct {
		ProfileId Id
		FieldId   Id
		Value     string
	}

	// Persister is an interface which provides an access to persistent layer
	Persister interface {
		GetMainPersister() MainPersister
		GetPartPersister(partId Id) PartPersister
	}

	// An transactional persister (has context dependant time)
	MainPersister interface {
	}

	// Partitioned persister
	PartPersister interface {
	}

	PersonsQuery struct {
		// Camera Id the request done for
		CamId Id
		// The maximum allowable max time.
		MaxLastSeenAt common.Timestamp
		// Request only this persons (MaxLastSeenAt and Limit will be disregarded)
		PersonIds []Id
		// How many to select
		Limit int
	}
)

// Known field types for profile fields description
const (
	FLD_TYPE_STRING FieldType = "string"
)

func (q *PersonsQuery) String() string {
	return fmt.Sprintf("{CamId=%s, PersonsIds=%v, MaxLastSeenAt=%d, Limit=%d}", q.CamId, q.PersonIds, q.MaxLastSeenAt, q.Limit)
}
