// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fpcp.proto

/*
Package fpcp is a generated protocol buffer package.

It is generated from these files:
	fpcp.proto

It has these top-level messages:
	Void
	Size
	Rectangle
	AuthToken
	Scene
	Frame
	Face
*/
package fpcp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Frame_Format int32

const (
	Frame_RAW Frame_Format = 0
	Frame_PNG Frame_Format = 1
)

var Frame_Format_name = map[int32]string{
	0: "RAW",
	1: "PNG",
}
var Frame_Format_value = map[string]int32{
	"RAW": 0,
	"PNG": 1,
}

func (x Frame_Format) String() string {
	return proto.EnumName(Frame_Format_name, int32(x))
}
func (Frame_Format) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

// Just use it like an empty message
type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Size struct {
	Width  uint32 `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *Size) Reset()                    { *m = Size{} }
func (m *Size) String() string            { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()               {}
func (*Size) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Size) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Size) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Rectangle struct {
	Left   int32 `protobuf:"varint,1,opt,name=left" json:"left,omitempty"`
	Top    int32 `protobuf:"varint,2,opt,name=top" json:"top,omitempty"`
	Right  int32 `protobuf:"varint,3,opt,name=right" json:"right,omitempty"`
	Bottom int32 `protobuf:"varint,4,opt,name=bottom" json:"bottom,omitempty"`
}

func (m *Rectangle) Reset()                    { *m = Rectangle{} }
func (m *Rectangle) String() string            { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()               {}
func (*Rectangle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rectangle) GetLeft() int32 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *Rectangle) GetTop() int32 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *Rectangle) GetRight() int32 {
	if m != nil {
		return m.Right
	}
	return 0
}

func (m *Rectangle) GetBottom() int32 {
	if m != nil {
		return m.Bottom
	}
	return 0
}

type AuthToken struct {
	Access string `protobuf:"bytes,1,opt,name=access" json:"access,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (m *AuthToken) Reset()                    { *m = AuthToken{} }
func (m *AuthToken) String() string            { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()               {}
func (*AuthToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthToken) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *AuthToken) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type Scene struct {
	Frame *Frame  `protobuf:"bytes,1,opt,name=frame" json:"frame,omitempty"`
	Faces []*Face `protobuf:"bytes,2,rep,name=faces" json:"faces,omitempty"`
}

func (m *Scene) Reset()                    { *m = Scene{} }
func (m *Scene) String() string            { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()               {}
func (*Scene) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Scene) GetFrame() *Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *Scene) GetFaces() []*Face {
	if m != nil {
		return m.Faces
	}
	return nil
}

type Frame struct {
	Id        string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp uint64       `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Size      *Size        `protobuf:"bytes,3,opt,name=size" json:"size,omitempty"`
	Data      []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Format    Frame_Format `protobuf:"varint,5,opt,name=format,enum=fpcp.Frame_Format" json:"format,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Frame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Frame) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Frame) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Frame) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Frame) GetFormat() Frame_Format {
	if m != nil {
		return m.Format
	}
	return Frame_RAW
}

type Face struct {
	Id   string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Rect *Rectangle `protobuf:"bytes,2,opt,name=rect" json:"rect,omitempty"`
}

func (m *Face) Reset()                    { *m = Face{} }
func (m *Face) String() string            { return proto.CompactTextString(m) }
func (*Face) ProtoMessage()               {}
func (*Face) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Face) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Face) GetRect() *Rectangle {
	if m != nil {
		return m.Rect
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "fpcp.Void")
	proto.RegisterType((*Size)(nil), "fpcp.Size")
	proto.RegisterType((*Rectangle)(nil), "fpcp.Rectangle")
	proto.RegisterType((*AuthToken)(nil), "fpcp.AuthToken")
	proto.RegisterType((*Scene)(nil), "fpcp.Scene")
	proto.RegisterType((*Frame)(nil), "fpcp.Frame")
	proto.RegisterType((*Face)(nil), "fpcp.Face")
	proto.RegisterEnum("fpcp.Frame_Format", Frame_Format_name, Frame_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SceneProcessorService service

type SceneProcessorServiceClient interface {
	// Authenticates the client. Server will respond appropriate "session_id" or "error".
	Authenticate(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*Void, error)
	// Sends the client scene information.
	OnScene(ctx context.Context, in *Scene, opts ...grpc.CallOption) (*Void, error)
}

type sceneProcessorServiceClient struct {
	cc *grpc.ClientConn
}

func NewSceneProcessorServiceClient(cc *grpc.ClientConn) SceneProcessorServiceClient {
	return &sceneProcessorServiceClient{cc}
}

func (c *sceneProcessorServiceClient) Authenticate(ctx context.Context, in *AuthToken, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/fpcp.SceneProcessorService/authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneProcessorServiceClient) OnScene(ctx context.Context, in *Scene, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/fpcp.SceneProcessorService/onScene", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SceneProcessorService service

type SceneProcessorServiceServer interface {
	// Authenticates the client. Server will respond appropriate "session_id" or "error".
	Authenticate(context.Context, *AuthToken) (*Void, error)
	// Sends the client scene information.
	OnScene(context.Context, *Scene) (*Void, error)
}

func RegisterSceneProcessorServiceServer(s *grpc.Server, srv SceneProcessorServiceServer) {
	s.RegisterService(&_SceneProcessorService_serviceDesc, srv)
}

func _SceneProcessorService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneProcessorServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpcp.SceneProcessorService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneProcessorServiceServer).Authenticate(ctx, req.(*AuthToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneProcessorService_OnScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scene)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneProcessorServiceServer).OnScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpcp.SceneProcessorService/OnScene",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneProcessorServiceServer).OnScene(ctx, req.(*Scene))
	}
	return interceptor(ctx, in, info, handler)
}

var _SceneProcessorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fpcp.SceneProcessorService",
	HandlerType: (*SceneProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "authenticate",
			Handler:    _SceneProcessorService_Authenticate_Handler,
		},
		{
			MethodName: "onScene",
			Handler:    _SceneProcessorService_OnScene_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fpcp.proto",
}

func init() { proto.RegisterFile("fpcp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x25, 0xbb, 0x4e, 0xaa, 0xcc, 0x96, 0xb2, 0x1a, 0x01, 0x8a, 0x2a, 0x84, 0x16, 0x73, 0x59,
	0x81, 0xb4, 0x87, 0xc0, 0xad, 0xa7, 0x5e, 0xca, 0x05, 0xa1, 0xca, 0x8b, 0xe0, 0x88, 0x5c, 0x67,
	0xd2, 0x58, 0x34, 0xf1, 0xca, 0x71, 0x41, 0xea, 0x5f, 0xf1, 0x87, 0xc8, 0x63, 0x6b, 0xa9, 0xc4,
	0x6d, 0xde, 0x9b, 0x19, 0xcf, 0xbc, 0x37, 0x06, 0xe8, 0x0f, 0xe6, 0xb0, 0x3b, 0x78, 0x17, 0x1c,
	0x8a, 0x18, 0xcb, 0x0a, 0xc4, 0x37, 0x67, 0x3b, 0xf9, 0x11, 0xc4, 0xde, 0x3e, 0x10, 0x3e, 0x87,
	0xf2, 0xb7, 0xed, 0xc2, 0xd0, 0x14, 0x9b, 0x62, 0xfb, 0x54, 0x25, 0x80, 0x2f, 0xa1, 0x1a, 0xc8,
	0xde, 0x0e, 0xa1, 0x59, 0x30, 0x9d, 0x91, 0xfc, 0x01, 0xb5, 0x22, 0x13, 0xf4, 0x74, 0x7b, 0x47,
	0x88, 0x20, 0xee, 0xa8, 0x0f, 0xdc, 0x59, 0x2a, 0x8e, 0x71, 0x0d, 0xcb, 0xe0, 0x0e, 0xdc, 0x55,
	0xaa, 0x18, 0xc6, 0x01, 0x9e, 0x5f, 0x5a, 0x32, 0x97, 0x40, 0x1c, 0x70, 0xe3, 0x42, 0x70, 0x63,
	0x23, 0x98, 0xce, 0x48, 0x5e, 0x40, 0x7d, 0x79, 0x1f, 0x86, 0xaf, 0xee, 0x27, 0x4d, 0xb1, 0x48,
	0x1b, 0x43, 0xf3, 0xcc, 0x23, 0x6a, 0x95, 0x51, 0xe4, 0x67, 0x32, 0x9e, 0xd2, 0x76, 0xb5, 0xca,
	0x48, 0x7e, 0x86, 0x72, 0x6f, 0x68, 0x22, 0x7c, 0x03, 0x65, 0xef, 0xf5, 0x48, 0xdc, 0xb7, 0x6a,
	0x57, 0x3b, 0xb6, 0xe1, 0x2a, 0x52, 0x2a, 0x65, 0x70, 0x03, 0x65, 0xaf, 0x0d, 0xcd, 0xcd, 0x62,
	0xb3, 0xdc, 0xae, 0x5a, 0xc8, 0x25, 0xda, 0xc4, 0x8a, 0x98, 0x90, 0x7f, 0x0a, 0x28, 0xb9, 0x05,
	0xcf, 0x60, 0x61, 0xbb, 0xbc, 0xc3, 0xc2, 0x76, 0xf8, 0x0a, 0xea, 0x60, 0x47, 0x9a, 0x83, 0x1e,
	0x93, 0x54, 0xa1, 0xfe, 0x11, 0xf8, 0x1a, 0xc4, 0x6c, 0x1f, 0x88, 0xf5, 0x1e, 0x1f, 0x8e, 0x5e,
	0x2b, 0xe6, 0xa3, 0x6d, 0x9d, 0x0e, 0x9a, 0x85, 0x9f, 0x2a, 0x8e, 0xf1, 0x1d, 0x54, 0xbd, 0xf3,
	0xa3, 0x0e, 0x4d, 0xb9, 0x29, 0xb6, 0x67, 0x2d, 0x3e, 0xda, 0x78, 0x77, 0xc5, 0x19, 0x95, 0x2b,
	0xe4, 0x39, 0x54, 0x89, 0xc1, 0x13, 0x58, 0xaa, 0xcb, 0xef, 0xeb, 0x27, 0x31, 0xb8, 0xfe, 0xf2,
	0x69, 0x5d, 0xc8, 0x0b, 0x10, 0x51, 0xc2, 0x7f, 0x1b, 0xbf, 0x05, 0xe1, 0xc9, 0x24, 0xbf, 0x56,
	0xed, 0xb3, 0xf4, 0xfa, 0xf1, 0x92, 0x8a, 0x93, 0xed, 0x00, 0x2f, 0xd8, 0xbe, 0x6b, 0xef, 0xa2,
	0xcd, 0xce, 0xef, 0xc9, 0xff, 0xb2, 0x86, 0xf0, 0x3d, 0x9c, 0xea, 0xfb, 0x30, 0xd0, 0x14, 0xac,
	0xd1, 0x81, 0x30, 0xf7, 0x1f, 0x0f, 0x75, 0x9e, 0x45, 0xc6, 0x8f, 0x85, 0x12, 0x4e, 0xdc, 0x94,
	0xce, 0x90, 0x7d, 0x67, 0xf0, 0xb8, 0xe6, 0xa6, 0xe2, 0x1f, 0xf9, 0xe1, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0xfa, 0x53, 0xc1, 0x9f, 0x02, 0x00, 0x00,
}
